### PR TITLE
NSIS Installer

### PR DESCRIPTION
**Pull request by Kangie**
This PR is to add an NSIS installer that enables configuration of mod keys under [main] at install time.

### CODE REVIEW

**Comment by Kangie** [comment]
So, I'm still working on this but it *should* be bugfixes of the NSIS script if I've read the docs correctly.

Unfortunately I can't get FO2tweaks to build on my dev machine at the moment. I'd appreciate any pointers so that I can test properly!

I get the following error that I haven't had a chance to track down when running `./extras/buildall.sh`

```bash
+ wine /home/xubuntuvm/dev/FO2tweaks/extra/bin/compile.exe -l -O2 -p -s -q -n gl_g_ammobox.ssl -o /home/xubuntuvm/dev/FO2tweaks/data/scripts/gl_g_ammobox.int
Compiling gl_g_ammobox.ssl
[Error] <upu.h>:38:45: Expected ';' at end of variable declaration
```

**Comment by burner1024** [comment]
Hey. Thanks for pull, although it'd be better to ask before spending a sizable effort.
I tried NSIS for UP/RP. Spent a few days on it, and in the end just had to drop it in favor of Inno. The syntax is horrible, and everything has to be done manually... I do prefer open source, but not that much.
About compilation error, which compile.exe version do you use? Try the latest one.

**Comment by Kangie** [comment]
Good catch. I'd forgotten to set the environment variable, and the default variable in the build script is apparently too old!

I'll update that default to the current ver as part of this PR.

Thanks for the feedback!

Honestly I haven't found NSIS *too* bad so far, but we'll see how I feel after a few more runs through...

**Comment by burner1024** [comment]
stale

**Pull request closed without merging**
