### PR TITLE
Add Ukrainian translation

### PR DESCRIPTION
**Pull request by IllusiveMan196**
Two unpoified game message files are broken for some reason, so requires fix (relevant strings are in .po file), third file is thankfully fine.

### CODE REVIEW

**Comment by burner1024** [comment]
Well, msg files are not supposed to be in UTF-8. They should be in corresponding windows encoding (cp1252 for western european, cp1251 for russian, etc). I don't know what encoding does windows use in ukranian, though.

Anyway, how do you plan to use this translation in game? Because as far as I know, there's no Ukranian translation for Fallout itself?

**Comment by FakelsHub** [comment]
У игры нет шрифта который бы поддерживал русскую кирилицу со специфичными символами используемые в укр. словах.
А нет шрифта потому, что никому в здравом уме не приходило в голоахву переводить игру на укр. язык.

**Comment by IllusiveMan196** [comment]
If and when I'll get to it. Still have to translate Wrye Bash at least. As for graphics, fonts, etc, just show me what to do, if it doesn't require some special knowledge of game structure or rare editors, probably I can do it (depending on amount of assets to be made). RP has like 50k strings, which is a lot (WB sits around 2-4k depending on where to get numbers from) but doable, not in one go though.

As for fonts: pretty much everything except for "є" is covered by existing fonts. Hard "г" can be ignored as barely any words actually use it (+ they aren't common in games), "і" exists in latin alphabet, "ї" as well, if it's not used in game, then use "іі" perhaps?

**Comment by burner1024** [comment]
> As for fonts: pretty much everything except for "є" is covered by existing fonts. Hard "г" can be ignored as barely any words actually use it (+ they aren't common in games), "і" exists in latin alphabet, "ї" as well, if it's not used in game, then use "іі" perhaps?

I wouldn't know, I have no knowledge of Ukrainian.

- Your PR is accepted, thank you. In future, though, it's preferable to use translation [system](https://tra.bgforge.net/). Direct edits to PO files require extra steps to be loaded, and direct edits to MSG files will be rejected as they are unusable.
- Still, there's no way to use Ukrainian in the game currently.
- First step to enabling is to create a Ukrainian font. See [FON](https://falloutmods.fandom.com/wiki/FON_File_Format) format reference. There's an editor for fonts. But you're on your own with that. (There's also [AAF](https://falloutmods.fandom.com/wiki/AAF_File_Format) fonts, which are use somewhere in interface, I think)
- Good luck with translation.

**Pull request merged**
